[package]
name = "algorithms_and_data_structures"
version = "0.1.0"
authors = ["iamveso <simon@softcom.ng>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
